[package]
name = "chip8_emu_driver"
version = "0.1.0"
authors = ["Kevin Brothaler <contact@digipom.com>"]

[dependencies]
rand = "0.3.14"
sdl2 = "0.25.0"

[dependencies.chip8_emu]
path = "../chip8_emu/"